-- Directorio de canchas de Mendoza, con datos reales (2026-09-13, a
-- pedido del usuario) -- extraídos de atcsports.io/results (plataforma
-- real de reserva de canchas), que listó 51 clubes de pádel en Mendoza.
-- De esos 51, 11 ya estaban cargados (con nombre parecido) desde el seed
-- original de 011_canchas_predictivo.sql -- se agregan acá SOLO los otros
-- 40, para no duplicar ni tocar los que ya tienen reseñas de demo
-- enganchadas (resenas_canchas.cancha_id); esos 11 se actualizan aparte en
-- 052_canchas_atc_detalle_existentes.sql. La zona es una estimación propia
-- en base a la dirección/coordenadas de cada club, no viene del dato
-- original. `descripcion` (cantidad de canchas, techadas/descubiertas,
-- superficie, amenities, horario) y `valores` (precio de referencia de la
-- franja consultada) tampoco vienen "guardados" tal cual en el dato
-- original -- se guardan ahora para tenerlos, todavía no se decidió si se
-- van a usar en pantalla.
insert into public.canchas (nombre, direccion, zona, telefono, descripcion, valores) values
  ('PACIFICO Padel', 'Perú 2280', 'Ciudad de Mendoza', '0261 205-4178',
   '6 canchas (0 techadas, 6 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Quincho · Lun a Vie 09:00-24:00hs',
   'Desde $32.000 los 90 min'),
  ('Terrazas Padel', 'Carlos Washington Lencinas 985', 'Ciudad de Mendoza', '0261 599-3232',
   '7 canchas (0 techadas, 7 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Estacionamiento, Ayuda Médica, Cumpleaños, Parrilla, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 08:00-01:30hs',
   'Desde $48.000 los 120 min'),
  ('PADEL INDEPENDENCIA', 'Arroyo 223', 'Godoy Cruz', '0261 235-2567',
   '3 canchas (0 techadas, 3 descubiertas, blindex-synthetic) · Vestuario, Gimnasio, Torneos, Cumpleaños, Parrilla, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 10:00-24:00hs',
   'Desde $32.000 los 90 min'),
  ('Dorrego Padel', 'Remedios de Escalada 2976, Guaymallén', 'Guaymallén', '0261 660-5530',
   '2 canchas (0 techadas, 2 descubiertas, blindex-synthetic) · Estacionamiento, Parrilla, Disposicion de paletas · Lun a Vie 14:00-24:00hs',
   null),
  ('El Ombu', 'Remedios de Escalada 3458, Guaymallén', 'Guaymallén', '0261 485-3898',
   '2 canchas (0 techadas, 2 descubiertas, synthetic/cement) · Wi-Fi, Vestuario, Estacionamiento, Ayuda Médica, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Quincho · Lun a Vie 14:00-24:00hs',
   'Desde $18.000 los 90 min'),
  ('J3 Sport Padel', 'Almirante Brown 2051', 'Godoy Cruz', '0261 709-8901',
   '3 canchas (0 techadas, 3 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 09:30-24:30hs',
   'Desde $30.000 los 90 min'),
  ('Fox Padel', 'Rodríguez Peña 2032', 'Guaymallén', '0261 399-4317',
   '4 canchas (0 techadas, 4 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Estacionamiento, Ayuda Médica, Cumpleaños, Parrilla, Quincho, Disposicion de paletas · Lun a Vie 15:00-24:30hs',
   null),
  ('Punto de Oro Sede Maipú', 'Alsina y Maza', 'Maipú', '0261 717-1141',
   '6 canchas (0 techadas, 6 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Estacionamiento, Torneos, Cumpleaños, Parrilla, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 14:00-24:00hs',
   'Desde $30.000 los 90 min'),
  ('Efecto Padel Indoor', 'Altos Hornos de Zapla y Terrada', 'Guaymallén', '0261 702-2127',
   '3 canchas (3 techadas, 0 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Estacionamiento, Ayuda Médica, Parrilla, Escuelita deportiva, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 10:00-24:00hs',
   'Desde $44.000 los 90 min'),
  ('Al Cubo Fútbol', 'Independencia 650 esq. Cubillos, Godoy Cruz', 'Godoy Cruz', '0261 672-3000',
   '2 canchas (0 techadas, 2 descubiertas, blindex-synthetic) · Vestuario, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Quincho · Lun a Vie 10:00-01:00hs',
   'Desde $36.000 los 90 min'),
  ('Marista Camp', 'Av. Champagnat 2045', 'Ciudad de Mendoza', '0261 221-1873',
   '4 canchas (0 techadas, 4 descubiertas, synthetic/blindex-synthetic) · Vestuario, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante · Lun a Vie 12:00-24:00hs',
   'Desde $28.000 los 90 min'),
  ('Los Duendes Pádel', 'Urquiza 1708, Guaymallén', 'Guaymallén', '0261 778-6256',
   '3 canchas (0 techadas, 3 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Gimnasio, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Colegios, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 08:00-24:00hs',
   'Desde $36.000 los 120 min'),
  ('Greengo Pádel Club', 'Bandera de los Andes 5965', 'Guaymallén', '0261 651-9015',
   '5 canchas (0 techadas, 5 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Estacionamiento, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 08:30-24:30hs',
   null),
  ('City Pádel', 'Perito Moreno 2699', 'Godoy Cruz', '0261 712-3415',
   '2 canchas (0 techadas, 2 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Estacionamiento, Torneos, Parrilla, Escuelita deportiva, Disposicion de paletas · Lun a Vie 10:00-24:30hs',
   null),
  ('Kondor Padel Club', 'Adolfo Villanueva 548', 'Maipú', '0261 710-8879',
   '9 canchas (0 techadas, 9 descubiertas, blindex-synthetic/synthetic) · Wi-Fi, Vestuario, Gimnasio, Estacionamiento, Torneos, Parrilla, Escuelita deportiva, Bar / Restaurante, Disposicion de paletas · Lun a Vie 08:00-24:30hs',
   'Desde $30.000 los 90 min'),
  ('Garden Pádel', 'Tapón Moyano s/n, cerca de Elpidio González', 'Guaymallén', '0261 690-8813',
   '3 canchas (0 techadas, 3 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Estacionamiento, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Quincho, Disposicion de paletas · Lun a Vie 10:00-24:00hs',
   'Desde $32.000 los 90 min'),
  ('Complejo Alsina', 'Alsina 2545', 'Maipú', '0261 697-4010',
   '2 canchas (2 techadas, 0 descubiertas, synthetic-wall) · Wi-Fi, Vestuario, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 10:00-24:30hs',
   'Desde $22.000 los 60 min'),
  ('Cofam Padel Center', 'Antonelli 300, Rodeo de la Cruz', 'Guaymallén', '0261 634-3232',
   '4 canchas (0 techadas, 4 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Gimnasio, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 08:30-01:00hs',
   'Desde $20.000 los 60 min'),
  ('Pasosurpadel', 'Emilio Civit 3074', 'Godoy Cruz', '0261 563-4054',
   '2 canchas (0 techadas, 2 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Gimnasio, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Colegios, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 09:00-24:00hs',
   'Desde $32.000 los 90 min'),
  ('H.Club', 'Terrada y A. Terrada', 'Godoy Cruz', '0261 711-0615',
   '4 canchas (0 techadas, 4 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Estacionamiento, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Disposicion de paletas · Lun a Vie 07:30-01:00hs',
   null),
  ('Africa Padel', 'Rodríguez Peña 3341', 'Guaymallén', '0261 513-9013',
   '2 canchas (0 techadas, 2 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Gimnasio, Estacionamiento, Parrilla, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 07:30-24:00hs',
   'Desde $24.000 los 90 min'),
  ('Indoor Mendoza Padel Center', 'Acceso Sur y Malabia', 'Godoy Cruz', '0261 747-4909',
   '16 canchas (16 techadas, 0 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Gimnasio, Estacionamiento, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 07:00-24:30hs',
   null),
  ('Morón Indoor', 'Bruno Morón y Gerónimo Ruiz', 'Maipú', '0261 336-2542',
   '2 canchas (2 techadas, 0 descubiertas, blindex-synthetic) · Lun a Vie 16:00-02:00hs',
   'Desde $40.000 los 90 min'),
  ('Gol Gana', 'Vieytes y Palma s/n', 'Maipú', '0261 263-3714',
   '2 canchas (0 techadas, 2 descubiertas, blindex-synthetic) · Vestuario, Estacionamiento, Ayuda Médica, Cumpleaños, Parrilla, Escuelita deportiva, Quincho, Disposicion de paletas · Lun a Vie 09:00-01:00hs',
   null),
  ('Ponce Padel', 'Carril Ponce 214, Rodeo de la Cruz', 'Guaymallén', '0261 244-1227',
   '6 canchas (0 techadas, 6 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 16:30-24:00hs',
   'Desde $34.000 los 90 min'),
  ('Boedo Camp', 'Boedo y Acceso Sur', 'Maipú', '0261 274-6808',
   '4 canchas (0 techadas, 4 descubiertas, blindex-synthetic/synthetic) · Wi-Fi, Vestuario, Gimnasio, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 07:00-24:00hs',
   'Desde $40.000 los 90 min'),
  ('Padel CPBM', 'Liniers s/n', 'Maipú', '0261 217-2099',
   '3 canchas (0 techadas, 3 descubiertas, blindex-synthetic) · Vestuario, Gimnasio, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 08:00-24:00hs',
   null),
  ('Padeltime Liceo Rugby Club', 'Vieytes y Boedo', 'Maipú', '0261 341-3994',
   '3 canchas (0 techadas, 3 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Estacionamiento, Torneos, Parrilla, Escuelita deportiva, Bar / Restaurante, Disposicion de paletas · Lun a Vie 14:00-23:00hs',
   null),
  ('Golden Pádel Club Mendoza', 'Acceso Este 10020, lateral norte', 'Maipú', '0261 570-3835',
   '3 canchas (1 techadas, 2 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 07:00-24:00hs',
   'Desde $38.000 los 90 min'),
  ('H.P.G Pádel', 'Padre Vera 181', 'Maipú', '0261 556-5620',
   '2 canchas (0 techadas, 2 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Gimnasio, Estacionamiento, Torneos, Parrilla, Bar / Restaurante, Disposicion de paletas · Lun a Vie 08:00-24:00hs',
   'Desde $28.000 los 90 min'),
  ('Gran Reserva Padel', 'San Martín 4871', 'Maipú', '0261 591-1738',
   '2 canchas (0 techadas, 2 descubiertas, blindex-synthetic) · Wi-Fi, Estacionamiento, Torneos, Cumpleaños, Escuelita deportiva, Bar / Restaurante, Disposicion de paletas · Lun a Vie 09:30-21:30hs',
   null),
  ('Coquimbito Padel', 'Carril Gómez 3084', 'Maipú', '0261 368-1167',
   '4 canchas (1 techadas, 3 descubiertas, synthetic) · Wi-Fi, Vestuario, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Quincho · Lun a Vie 16:00-23:30hs',
   'Desde $28.000 los 90 min'),
  ('Terra Padel', 'Vieytes esquina Bulnes', 'Maipú', '0261 416-4666',
   '5 canchas (0 techadas, 5 descubiertas, synthetic) · Wi-Fi, Estacionamiento, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Disposicion de paletas · Lun a Vie 07:30-24:00hs',
   'Desde $36.000 los 90 min'),
  ('Pro Court', 'Ruta Provincial 82 esq. Chaco, Vistalba', 'Luján de Cuyo', '0261 219-7182',
   '8 canchas (4 techadas, 4 descubiertas, blindex-synthetic) · Wi-Fi, Gimnasio, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Escuelita deportiva, Bar / Restaurante, Disposicion de paletas · Lun a Vie 08:00-23:30hs',
   null),
  ('Vista Pádel Club', 'Ozamis Sur 1605', 'Maipú', '0261 778-8066',
   '4 canchas (0 techadas, 4 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Disposicion de paletas · Lun a Vie 15:00-23:30hs',
   'Desde $44.000 los 120 min'),
  ('Padel CRYDAA', 'Maza 4210, Cruz de Piedra', 'Maipú', '0261 279-5630',
   '4 canchas (0 techadas, 4 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Gimnasio, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Bar / Restaurante, Quincho, Disposicion de paletas · Lun a Vie 09:00-24:00hs',
   'Desde $30.000 los 90 min'),
  ('Club Vistalba', 'Guardia Vieja 1428, Vistalba', 'Luján de Cuyo', '0261 664-0584',
   '3 canchas (0 techadas, 3 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Gimnasio, Estacionamiento, Ayuda Médica, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Colegios, Bar / Restaurante, Quincho · Lun a Vie 09:00-24:00hs',
   'Desde $32.000 los 90 min'),
  ('Olivos Premier Padel', 'Portillo de Piuquenes 1451', 'Luján de Cuyo', '0261 774-2902',
   '3 canchas (0 techadas, 3 descubiertas, blindex-synthetic) · Wi-Fi, Estacionamiento, Torneos, Cumpleaños, Escuelita deportiva, Disposicion de paletas · Lun a Vie 10:00-24:30hs',
   'Desde $36.000 los 90 min'),
  ('Azcuenaga Padel', 'Azcuenaga 3432, Luján de Cuyo', 'Luján de Cuyo', '0261 756-3824',
   '3 canchas (0 techadas, 3 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Estacionamiento, Torneos, Cumpleaños, Parrilla, Escuelita deportiva, Disposicion de paletas · Lun a Vie 14:00-23:30hs',
   'Desde $40.000 los 120 min'),
  ('Vistalba Open Padel', 'Roque Sáenz Peña 2972, Vistalba', 'Luján de Cuyo', '0261 555-3340',
   '4 canchas (0 techadas, 4 descubiertas, blindex-synthetic) · Wi-Fi, Vestuario, Estacionamiento, Torneos, Parrilla, Escuelita deportiva, Bar / Restaurante, Disposicion de paletas · Lun a Vie 09:00-23:30hs',
   'Desde $40.000 los 90 min');
