// Consejos de pádel (2026-10-03). Cada consejo está escrito con palabras
// propias a partir de una de las obras de FUENTES (que pertenecen a sus
// autores): no se copian frases. `f` = fuente, `p` = página de la obra donde
// está la idea, `c` = categoría. Se filtraron automáticamente los que
// repetían 6 o más palabras seguidas del original.
// Las guías de PadelStar son gratuitas (padelstar.es/guias-de-padel); el libro
// es una obra publicada: por eso solo se linkea la web de las guías.
export const FUENTES = {
  g1: { nombre: "PadelStar · Guía 1: Mandamientos del pádel", url: "https://padelstar.es/guias-de-padel/" },
  g2: { nombre: "PadelStar · Guía 2: Empuñaduras y posicionamiento en pista", url: "https://padelstar.es/guias-de-padel/" },
  g3: { nombre: "PadelStar · Guía 3: Saque, resto y golpes de fondo", url: "https://padelstar.es/guias-de-padel/" },
  g4: { nombre: "PadelStar · Guía 4: El remate de pádel", url: "https://padelstar.es/guias-de-padel/" },
  libro: { nombre: "Pádel: Enseñanza y Aprendizaje", autores: "José Antonio Arranz, Patty Llaguno y Eli Amatriain" },
};

// Orden en que se muestran las categorías.
export const CATEGORIAS = ["tactica", "tecnica", "saque-resto", "remate", "posicion", "mental", "fisico", "lesiones", "alimentacion", "etiqueta", "reglas"];

export const CONSEJOS = [
  { id: 1, c: "mental", t: "Llevá bien el tanteo. No se juega igual una bola con 15-0 a favor que una de quiebre: ajustá el riesgo según lo que está en juego en ese punto.", f: "g1", p: 3 },
  { id: 2, c: "tecnica", t: "Bolas muy bajas de drive: probá el agarre este de revés. Deja la cara de la pala más abierta y te permite levantar pelotas que casi rozan el piso.", f: "g2", p: 10 },
  { id: 3, c: "mental", t: "En pádel pesan igual la técnica, la táctica, el físico y la cabeza. Si descuidás alguno, los otros se resienten, así que buscá equilibrio.", f: "g4", p: 4 },
  { id: 4, c: "remate", t: "Pegá la pelota adelante tuyo, sobre la línea entre tu cabeza y el lugar al que apuntás. Ahí podés estirar todo el brazo y sacar más potencia.", f: "g4", p: 9 },
  { id: 5, c: "tecnica", t: "Mantené los pies en movimiento todo el tiempo, aunque la pelota parezca fácil. Frená recién justo antes de pegar, y así ganás control en el golpe.", f: "g1", p: 16 },
  { id: 6, c: "mental", t: "Traerte la bola con el remate no sale rápido ni fácil. Hace falta constancia, paciencia y entrenar bien, sin frustrarte si tarda en salir.", f: "g4", p: 5 },
  { id: 7, c: "tecnica", t: "Después de tirar un globo: si pasó a los rivales, subí a la red; si no los superó, quedate cerca de la línea de fondo para defender mejor un posible remate.", f: "g1", p: 15 },
  { id: 8, c: "fisico", t: "Para jugar mejor, entrená la agilidad y la salida corta explosiva más que la fuerza máxima: en el pádel casi todas las carreras son cortas, de arranque y frenada rápidos.", f: "libro", p: 102 },
  { id: 9, c: "posicion", t: "Hablá con tu compañero durante el partido, sobre todo con las bolas bajas o los globos al centro. Acordar quién va a qué pelota te da un instante extra para prepararte.", f: "g1", p: 4 },
  { id: 10, c: "remate", t: "En el remate rápido y profundo, no bajes el codo por debajo del hombro. Tené la pala detrás de la nuca y pegá adelante, con el otro brazo arriba.", f: "g4", p: 14 },
  { id: 11, c: "lesiones", t: "La pelota cambia con el clima: con calor rebota más, con frío pesa más y va más lenta. En lugares altos corre más, y en lugares húmedos el juego se hace más lento. Ajustá tus golpes a eso.", f: "libro", p: 200 },
  { id: 12, c: "tactica", t: "Después de un punto brillante, no busques otro mejor enseguida. Bajá un cambio y seguí jugando con margen de seguridad: un punto espectacular vale lo mismo que uno simple.", f: "g1", p: 5 },
  { id: 13, c: "saque-resto", t: "Con el primer saque rival, lo más seguro es restar por abajo al jugador que sacó: viene en movimiento hacia la red. El globo dejalo para el segundo saque.", f: "g3", p: 26 },
  { id: 14, c: "tecnica", t: "El revés liftado exige una muñeca fuerte: entrás desde abajo y acelerás la pala al final. Sirve cuando el rival está lejos de la red y querés que la bola baje a sus pies.", f: "g3", p: 56 },
  { id: 15, c: "fisico", t: "Antes de entrar a la cancha, trotá unos cinco minutos y hacé algo de elongación. Vas a responder más rápido en los primeros puntos y bajás el riesgo de lesionarte.", f: "g1", p: 4 },
  { id: 16, c: "mental", t: "Antes de perder el partido en la cabeza, preguntate si el rival no jugó mejor. Perder también enseña, y la derrota es parte del camino para disfrutar más las victorias.", f: "g1", p: 9 },
  { id: 17, c: "posicion", t: "Postura de espera: rodillas apenas flexionadas, torso un poco inclinado adelante, codos levemente adelantados y peso en la parte delantera de los pies.", f: "g2", p: 16 },
  { id: 18, c: "remate", t: "Para rematar, apuntá a la pelota con la mano libre como si fuera una mira y agarrala lo más alto posible, delante de los ojos. No hace falta saltar salvo que la situación te obligue.", f: "libro", p: 172 },
  { id: 19, c: "posicion", t: "Moveos con tu compañero como si fueran un solo bloque, a la manera de un limpiaparabrisas: cuando uno sale a la pelota, el otro se corre y mantiene la distancia para tapar el hueco.", f: "libro", p: 83 },
  { id: 20, c: "reglas", t: "Un saque que toca la red y cae bien se repite. Si es el primer saque, se repite el punto completo con dos saques; si es el segundo, solo se repite ese saque.", f: "g3", p: 11 },
  { id: 21, c: "posicion", t: "Cubrí el medio de la cancha. Ahí se pierden muchos puntos por dudas entre los dos, así que hablá con tu compañero y decidan antes quién se hace cargo de esas bolas.", f: "g1", p: 3 },
  { id: 22, c: "saque-resto", t: "Al sacar soltá la pelota para que caiga y pique, no la tires hacia abajo. Si le das impulso, se desvía y pierdes el control del golpe.", f: "g3", p: 16 },
  { id: 23, c: "tecnica", t: "Usá la mano libre en el drive para guiar la pala. Si la soltás, la pala tiende a caerse; agarrándola bien girás el cuerpo y pegás con más eficiencia.", f: "g2", p: 13 },
  { id: 24, c: "saque-resto", t: "Para restar, ponete de costado o semi-costado y pegá con la pelota delante del cuerpo. Con ese punto de impacto aumentan mucho las chances de un buen resto.", f: "g3", p: 24 },
  { id: 25, c: "remate", t: "Apuntá el remate a la pared de fondo rival, en línea recta desde donde estás. Cuanto menos recorrido haga la bola, más fácil es traerla a tu lado.", f: "g4", p: 9 },
  { id: 26, c: "saque-resto", t: "Un buen saque no siempre gana el punto directo, pero te ayuda a subir a la red en buena posición. Pensá el saque como el inicio de la jugada, no solo como el golpe.", f: "g3", p: 13 },
  { id: 27, c: "remate", t: "Antes de buscar más fuerza en el remate, afiná la técnica. Pegás mejor, gastás menos energía y cuidás el hombro de lesiones.", f: "g4", p: 7 },
  { id: 28, c: "saque-resto", t: "En el resto no te la juegues con un golpe fuerte y bajo. Mejor devolvé con un globo cruzado al que saca o paralelo al que está en la red, así forzás el error de ellos.", f: "g1", p: 4 },
  { id: 29, c: "posicion", t: "Evitá la zona de nadie, la franja entre la red y la línea de saque. Ahí te tiran a los pies y te obligan a volear bajo o a jugar bote pronto, que es muy difícil.", f: "g2", p: 25 },
  { id: 30, c: "saque-resto", t: "No te obsesiones con la fuerza al sacar. Un buen efecto y la dirección correcta valen más que pegarle fuerte; si querés potencia, necesitás más control.", f: "g3", p: 17 },
  { id: 31, c: "mental", t: "Si estás muy nervioso, respirá lento y profundo y decite algo como tranquilo. Si estás dormido, mové las piernas y respirá más rápido. Buscá el punto medio entre excitado y relajado.", f: "libro", p: 114 },
  { id: 32, c: "tactica", t: "Después de pegar, movete enseguida a tu posición. Mientras tu bola cruza la red, volvé; no te quedes mirando qué hace ni quién la devuelve.", f: "g2", p: 18 },
  { id: 33, c: "tecnica", t: "Agarrá la pala con la empuñadura continental: como darle la mano a la raqueta. Sirve para casi todos los golpes y no te hace perder tiempo cambiando el agarre en pleno punto.", f: "g2", p: 7 },
  { id: 34, c: "tactica", t: "Si a tu compañero le llegan todas las pelotas, jugá varias en paralelo para repartir el trabajo y que el rival cambie su foco.", f: "libro", p: 84 },
  { id: 35, c: "tecnica", t: "Terminá la derecha con la pala adelante, a la altura del ojo, sin hacer un swing largo como en el tenis. Pasarte da profundidad y una bola alta que le sirve al rival.", f: "g3", p: 39 },
  { id: 36, c: "remate", t: "Al remate a los picos, buscá los rincones donde se juntan la pared y la alambrado. Complicás al rival, pero no esperes acertar al primero: paciencia.", f: "g4", p: 12 },
  { id: 37, c: "tecnica", t: "La volea se juega más con los pies que con el brazo. Pensá en dos tiempos: paso y golpe juntos, con una preparación cortita y el peso yendo hacia la red.", f: "libro", p: 61 },
  { id: 38, c: "reglas", t: "Si no estás listo para recibir, podés frenar el juego. Pero si ya intentaste devolver el saque, no vale decir después que no estabas preparado.", f: "g3", p: 11 },
  { id: 39, c: "remate", t: "Flexioná un poco las rodillas antes de pegar y estirate al subir, como un resorte. Esa extensión de piernas le suma potencia al remate.", f: "g4", p: 7 },
  { id: 40, c: "tecnica", t: "Terminá siempre el golpe con el brazo suelto, relajado y buscando el equilibrio. Una buena terminación suele mostrar que lo anterior salió bien, y te cuida tendones y articulaciones.", f: "libro", p: 73 },
  { id: 41, c: "lesiones", t: "El revés con mal agarre y sin fuerza de piernas y cuerpo suele terminar en dolor de codo. Aprendelo con la mano bien colocada y usá todo el cuerpo, no solo el brazo.", f: "libro", p: 130 },
  { id: 42, c: "tactica", t: "No le tengas miedo a las paredes: para defender bien tenés que dominar la salida de fondo y la doble pared. Practicalas hasta que no te asusten.", f: "g2", p: 48 },
  { id: 43, c: "tecnica", t: "Cambiar de empuñadura durante el punto es cosa de jugadores con nivel y mucho entrenamiento. Si recién arrancás, priorizá dominar un solo agarre.", f: "g2", p: 12 },
  { id: 44, c: "alimentacion", t: "Tomá agua a lo largo del día y también mientras jugás, sin esperar a tener sed. Después del partido, aunque no tengas hambre, comé algo para recuperarte.", f: "g1", p: 40 },
  { id: 45, c: "tactica", t: "Estudiá a los rivales en el peloteo previo: si son zurdos, si juegan con efecto, cuál es su golpe débil (suele ser el revés) y si prefieren atacar o defender. Comentalo con tu compañero.", f: "g1", p: 21 },
  { id: 46, c: "tecnica", t: "Terminá cada golpe volviendo a la postura de espera y recuperando el equilibrio. Después de varios remates y bandejas seguidos es donde más se pierde ese hábito.", f: "g2", p: 17 },
  { id: 47, c: "tactica", t: "En defensa, devolvé cruzado: la pelota hace un recorrido más largo y es menos arriesgado que jugarla en paralelo. Y no te quedes mirando tu bola: recuperá la posición.", f: "g3", p: 71 },
  { id: 48, c: "saque-resto", t: "Sacá con efecto cortado, de arriba hacia abajo: la pelota rebota poco y le complica la devolución al rival, sobre todo si va pegada a la pared.", f: "g3", p: 16 },
  { id: 49, c: "tecnica", t: "Cortado, plano y liftado sirven para cosas distintas: plano para dar velocidad, cortado para que la bola pique bajo contra la pared, liftado para buscar los pies del rival.", f: "g3", p: 36 },
  { id: 50, c: "tactica", t: "Desde el fondo, si te vienen a atacar, jugá bajito y por el centro. Y apenas puedas, mandá un buen globo para sacar a los rivales de la red y subir vos.", f: "libro", p: 81 },
  { id: 51, c: "tecnica", t: "En el revés, la mano libre te obliga a girar los hombros, y eso da un golpe más parejo y preciso. No la olvides en la preparación.", f: "g2", p: 13 },
  { id: 52, c: "posicion", t: "Muévanse como pareja y no uno atrás y otro adelante. Avancen y retrocedan juntos, parejos como en el metegol, para dejar pocos huecos y cerrar los ángulos.", f: "g1", p: 5 },
  { id: 53, c: "tecnica", t: "Con las paredes, ganás tiempo pero también se lo das al rival para tomar la red. Si podés pegar antes del rebote, jugás más rápido y ofensivo. Si queda muy baja, tirá un globo.", f: "g1", p: 15 },
  { id: 54, c: "lesiones", t: "Estar concentrado ayuda a prevenir lesiones, sobre todo en los tobillos y las muñecas. Fijate en el piso y en las bolas rodando, y usá siempre calzado apropiado para pádel.", f: "g1", p: 36 },
  { id: 55, c: "tactica", t: "Si el rival está en el fondo, jugá cortado para que rebote bajo en la pared. Si está volando en la red, mejor plano o liftado: el cortado flota y le da tiempo.", f: "g3", p: 35 },
  { id: 56, c: "tecnica", t: "En la derecha ponete de costado, aunque sea cómodo pegar de frente. De frente perdés control, la bola sale alta y le regalás un remate al rival.", f: "g3", p: 39 },
  { id: 57, c: "saque-resto", t: "Entrená el saque y el resto más de lo que creés. Casi nadie los practica porque son más estáticos, pero son los primeros golpes de cada punto.", f: "g3", p: 24 },
  { id: 58, c: "tecnica", t: "En la volea no cambies el agarre entre drive y revés. La pelota viene muy rápido y no hay tiempo; mantené la continental y reaccioná más rápido en los cruces de red.", f: "g2", p: 9 },
  { id: 59, c: "tactica", t: "Muévanse en pareja como un limpiaparabrisas: si uno va a un costado a devolver, el compañero se desplaza al mismo lado cubriendo el centro y sin dejar huecos.", f: "g2", p: 31 },
  { id: 60, c: "tecnica", t: "Para el remate por tres o un remate con efecto que quieras hacer volver a tu lado, algunos jugadores avanzados usan el agarre este de revés. Es para quien ya domina la continental.", f: "g2", p: 10 },
  { id: 61, c: "tactica", t: "El pádel se gana con pocos errores. Aunque seas mejor técnicamente, no apures el punto: armalo de a poco y definí recién cuando tengas la jugada clara.", f: "g1", p: 4 },
  { id: 62, c: "remate", t: "Con la bandeja podés mantener la red: si estás defendiendo, hacela suave y profunda; si atacás, cortala para que baje y apenas pique en la cancha rival.", f: "libro", p: 184 },
  { id: 63, c: "tecnica", t: "Cuando le pegás a la pelota, mirala fijo y mantené la pala firme. Seguí el golpe un poco hacia adelante: ahí es donde se controlan la dirección y la profundidad.", f: "libro", p: 72 },
  { id: 64, c: "alimentacion", t: "No pruebes comidas nuevas el día de un partido importante. Lo que comas antes de jugar probalo antes, en entrenamientos, para saber cómo te cae.", f: "g1", p: 48 },
  { id: 65, c: "lesiones", t: "La continental es un agarre natural que no retuerce la muñeca. Usarla en todos los golpes ayuda a cuidar la articulación y a que no te lastimes.", f: "g2", p: 7 },
  { id: 66, c: "tecnica", t: "Antes de cada golpe, agarrá la posición de espera: pies un poco más abiertos que los hombros, apoyo en la parte delantera, rodillas flexionadas. Así arrancás rápido para cualquier lado.", f: "libro", p: 65 },
  { id: 67, c: "posicion", t: "En la red, ajustá tu distancia a tu rapidez: si anticipás bien y sos ágil, podés estar más adelante y volear fuerte; si sos más lento, quedate un poco más atrás para cubrir el globo.", f: "g2", p: 29 },
  { id: 68, c: "lesiones", t: "Flexionar la muñeca en el impacto del revés es una causa frecuente de epicondilitis. Mantenela firme y acompañá con el cuerpo en vez de latiguear.", f: "g3", p: 52 },
  { id: 69, c: "fisico", t: "Calentá entre 10 y 20 minutos antes de jugar: empezá suave con trote y movilidad, subí la intensidad de a poco y terminá con golpes y desplazamientos parecidos al partido.", f: "libro", p: 103 },
  { id: 70, c: "posicion", t: "Si sos principiante, jugá en los dos lados de la cancha. Especializarte demasiado pronto te limita; a los más avanzados también les conviene dedicar un rato al otro lado.", f: "g3", p: 59 },
  { id: 71, c: "tactica", t: "Conocé tu propio juego: tus mejores y peores golpes, tu físico y si te sentís mejor defendiendo o atacando. Después armá la táctica con tu compañero, no solo con comentarios de afuera.", f: "g3", p: 63 },
  { id: 72, c: "remate", t: "Soltá la muñeca al rematar y acompañá el giro del antebrazo. La pala tiene que llegar bien perpendicular a la pelota, sin rigidez.", f: "g4", p: 10 },
  { id: 73, c: "tactica", t: "Globo solo si es profundo y seguro. Si no estás cómodo en el fondo, jugá por abajo hacia el centro: es más difícil que te ganen con volea que con un remate fácil.", f: "g3", p: 71 },
  { id: 74, c: "tecnica", t: "Armá corto cuando la pelota viene rápida, queda pegada a la pared o vas de bote pronto. Armá más amplio si te da tiempo, por ejemplo con una bola lenta o que rebota.", f: "g3", p: 6 },
  { id: 75, c: "lesiones", t: "Mucho pádel de golpe cansa a músculos y articulaciones. Respetá tiempos de recuperación entre partidos y no juegues de más si recién arrancás, aunque se vea fácil.", f: "g1", p: 37 },
  { id: 76, c: "tactica", t: "Atacando, apuntá a los huecos, a las paredes o al centro de la cancha para generar duda sobre quién la agarra. Las voleas cruzadas con rebote también incomodan mucho.", f: "g2", p: 50 },
  { id: 77, c: "mental", t: "Si te ponés en ventaja, no subestimes al rival ni te relajes. Muchas derrotas vienen de ganar un par de games fáciles, confiarse y empezar a cometer errores tontos.", f: "g1", p: 9 },
  { id: 78, c: "tactica", t: "Si ves que vas a llegar apurado a la pelota, no la fuerces con un remate de potencia. Quedaría fácil para el rival, mejor correr al fondo.", f: "g4", p: 11 },
  { id: 79, c: "saque-resto", t: "Un resto liftado baja rápido hacia los pies del rival que sube a la red y lo obliga a volear bajo. Si jugás de revés es un recurso muy usado.", f: "g3", p: 58 },
  { id: 80, c: "tactica", t: "Cuando se muevan en bloque, cubrí primero la bola paralela, que llega rápido. La cruzada recorre más cancha y te da más tiempo para reaccionar.", f: "g2", p: 30 },
  { id: 81, c: "remate", t: "Con rivales al fondo, probá un remate fuerte y más bajo para acelerar la bola, sin buscar que vuelva. Alternalo con el de potencia y los descolocás.", f: "g4", p: 11 },
  { id: 82, c: "tactica", t: "El frío y la humedad hacen que la pelota pese más y bote poco; el calor la hace más viva y rebotona. Ajustá tu juego a eso, y entrená tus globos si hay techo bajo.", f: "g1", p: 22 },
  { id: 83, c: "fisico", t: "Entrená el juego de pies: con conitos, una escalera de agilidad o una rejilla alcanza. Hacé al menos una sesión por semana, de lo fácil a lo difícil.", f: "g2", p: 36 },
  { id: 84, c: "posicion", t: "Para elegir lado con tu pareja: el zurdo suele ir a la derecha; el que mejor remata, resta o tiene más nivel y físico va al revés; el que tiene mejor volea de revés va a la derecha.", f: "g3", p: 61 },
  { id: 85, c: "saque-resto", t: "Variá el saque: alterná pegado al vidrio, a la T, al cuerpo, cortos y largos. Si el rival no sabe qué viene, ya tiene la mitad del trabajo perdido.", f: "g3", p: 22 },
  { id: 86, c: "tactica", t: "Peleá por la red: es donde más puntos se ganan. Ahí el recorrido de la pala tiene que ser corto y rápido, y reaccionar con reflejos. Quedarse siempre atrás hace difícil ganar.", f: "g1", p: 5 },
  { id: 87, c: "saque-resto", t: "Regla del saque: pies detrás de la línea y sin pisarla, pelota por debajo de la cintura, al menos un pie en el piso, sin caminar ni saltar, y en diagonal.", f: "g3", p: 14 },
  { id: 88, c: "mental", t: "Nunca des un partido por perdido. Siempre se puede remontar si mantenés la cabeza fría, seguís jugando seguro y esperás que los rivales se aflojen.", f: "g1", p: 3 },
  { id: 89, c: "saque-resto", t: "Primera meta del resto: que la pelota entre. Fallarlo es regalar el punto, igual que una doble falta. Después pensá en la ubicación.", f: "g3", p: 25 },
  { id: 90, c: "mental", t: "Si un golpe te sale mal, no te quedes pensando en el punto anterior ni asumas que te va a pasar igual. Cortá con esa idea y concentrate en la próxima pelota.", f: "g1", p: 9 },
  { id: 91, c: "tactica", t: "Cuando volees, tené la intención de definir el punto. Si te acostumbrás a bloquear de manera defensiva, después cuesta mucho cambiar ese hábito.", f: "libro", p: 159 },
  { id: 92, c: "remate", t: "Para acomodarte a la pelota, usá pasos cortos de costado y mantené el perfil. Evitá correr de frente, que te desarma la postura del golpe.", f: "g4", p: 10 },
  { id: 93, c: "tactica", t: "Rematá para definir solo si la pelota te queda adelante y vos estás cómodo y cerca de la red. Si tenés que retroceder, la falla es de elección.", f: "g4", p: 9 },
  { id: 94, c: "tecnica", t: "Al defender, hacé un armado corto de la pala y ajustá su altura según cómo baje la bola del vidrio: bola baja, armado bajo.", f: "g2", p: 46 },
  { id: 95, c: "tactica", t: "Defendiendo, mantenete activo y concentrado: pasitos cortos, atención al juego. Prefiere cruzado, porque la bola viaja más y el golpe tiene menos riesgo que el paralelo.", f: "g2", p: 48 },
  { id: 96, c: "tecnica", t: "Usá la empuñadura continental como base: te deja jugar casi todos los golpes sin cambiar la mano. Cuesta más al principio, pero es la que más te va a servir con el tiempo.", f: "libro", p: 57 },
  { id: 97, c: "mental", t: "Hablá con tu compañero antes y durante el partido. Si cada uno juega por su lado sin avisar, se pisan y quedan huecos en la cancha.", f: "libro", p: 83 },
  { id: 98, c: "tecnica", t: "Antes de cada golpe volvé a la posición de espera: pies al ancho de hombros, rodillas un poco flexionadas y la pala adelante, a la altura del pecho. No la dejes caer.", f: "g3", p: 3 },
  { id: 99, c: "alimentacion", t: "Antes de jugar evitá comidas pesadas o grasosas. Dejá pasar unas horas desde la comida principal y elegí algo liviano con hidratos, como pasta o fruta.", f: "g1", p: 43 },
  { id: 100, c: "tactica", t: "Un globo corto te deja con un remate encima. Hacelo siempre profundo; y si estás incómodo, jugá bajo por abajo sin globo para que el rival tenga que ganarla con una volea.", f: "g2", p: 48 },
  { id: 101, c: "saque-resto", t: "Pegale al saque cuando la pelota está en lo más alto del bote, siempre por debajo de la cintura. Ahí es donde más cuesta a los que recién empiezan.", f: "g3", p: 16 },
  { id: 102, c: "tactica", t: "Si te falta tiempo para reubicarte, tirá un globo: te regala segundos para volver. A veces conviene un golpe suave que ayude a los dos a acomodarse, antes que lucirte.", f: "g2", p: 18 },
  { id: 103, c: "tecnica", t: "En el revés mantené la muñeca firme todo el golpe y no gires los hombros al final. El brazo libre va hacia atrás mientras la pala va adelante.", f: "g3", p: 52 },
  { id: 104, c: "tactica", t: "Subí a la red preparado para la peor pelota, la más rápida y mejor dirigida. Con esa lista, las lentas y altas te sobran de tiempo para definir.", f: "g2", p: 40 },
  { id: 105, c: "saque-resto", t: "En el primer saque podés arriesgar un poco para incomodar al rival y arrancar el punto mandando. Si fallás, el segundo ya tiene que ser más seguro.", f: "libro", p: 82 },
  { id: 106, c: "tactica", t: "Antes de pensar en pegarle fuerte, asegurate de que la bola pase la red y quede adentro. Sin control, la potencia no sirve: primero constancia, después dirección y recién ahí velocidad.", f: "libro", p: 80 },
  { id: 107, c: "fisico", t: "Al terminar el partido, dedicá unos diez minutos a elongar los músculos que más trabajaron. Al día siguiente los dolores musculares te van a molestar bastante menos.", f: "g1", p: 5 },
  { id: 108, c: "tactica", t: "Perderle el miedo a las paredes es clave para defender. Un gran jugador de tenis no te gana en pádel hasta que domina las salidas de pared.", f: "g3", p: 71 },
  { id: 109, c: "tecnica", t: "Todo golpe se arma de atrás: si armás largo ganás potencia pero pegás más tarde; si armás corto ganás control. Elegí según lo que necesite la jugada.", f: "g3", p: 4 },
  { id: 110, c: "tactica", t: "Contra rivales que defienden muy bien y desgastan con globos, probá atacar desde el fondo: dejalos venir a la red y apuntá a sus voleas y a sus remates, que suelen ser lo flojo.", f: "g2", p: 41 },
  { id: 111, c: "etiqueta", t: "Tirarle el remate al cuerpo del rival es una jugada válida pero agresiva. En una pachanga con amigos, mejor no usarla.", f: "g4", p: 14 },
  { id: 112, c: "tactica", t: "No te quedes toda la tarde atrás defendiendo: los puntos se ganan en la zona de ataque cerca de la red. Buscá un buen globo para empujar a los rivales y subir.", f: "g2", p: 19 },
  { id: 113, c: "saque-resto", t: "Al restar, parate más cerca de la pared lateral que en una defensa normal, pero cuidá el medio por si te sacan hacia ahí. Los dos de la pareja, en la misma posición.", f: "g2", p: 28 },
  { id: 114, c: "tactica", t: "Un globo por encima de los rivales te hace pasar de defender en las paredes a atacar y tomar la red. Usalo seguido: complica a los rivales y fuerza sus errores.", f: "g1", p: 4 },
  { id: 115, c: "fisico", t: "Muchos errores son de pies, no de técnica. Mantenelos activos con saltitos y pasos cortos, así reaccionás antes y llegás mejor posicionado a la pelota.", f: "g2", p: 33 },
  { id: 116, c: "posicion", t: "Poné la mano libre en el centro de la pala mientras esperás. Equilibra el cuerpo y ya te deja lista la preparación para un revés.", f: "g2", p: 16 },
  { id: 117, c: "remate", t: "Un buen remate también tiene que pasar bien alto sobre la red, a más de 2 metros. Así el rival que se adelantó para anticipar no llega.", f: "g4", p: 10 },
  { id: 118, c: "posicion", t: "La espera no es una foto: orientá el cuerpo hacia donde está la bola en cada momento y hacé saltitos o pasitos cortos de ajuste para no quedarte clavado.", f: "g2", p: 16 },
  { id: 119, c: "tactica", t: "Fijate en las bolas y el clima: con frío o humedad la pelota pesa y pica poco; con calor se pone más viva y rebota más. Ajustá tus golpes de definición.", f: "g3", p: 66 },
  { id: 120, c: "saque-resto", t: "Apostá a tu primer saque: profundo, con algo de efecto, pero seguro. Entrar con el primero incomoda al rival; el segundo suele salir corto y les deja la red servida.", f: "g1", p: 3 },
  { id: 121, c: "tecnica", t: "Si venís jugando con otro agarre y te sale cómodo, no pasa nada: no significa que pegues mal. Eso sí, probá acercarte de a poco a la continental cuando tengas más confianza.", f: "g2", p: 3 },
  { id: 122, c: "mental", t: "Si algo sale mal, buscá la causa en lo que podés cambiar, como el esfuerzo y la preparación, y no en la suerte o en la cancha. Así se progresa.", f: "libro", p: 109 },
  { id: 123, c: "posicion", t: "Pensá la cancha en tres zonas: cerca de la red atacás, en el medio solo pasás rápido y sin arriesgar, y al fondo defendés. Intentá no quedarte clavado en la zona del medio.", f: "libro", p: 81 },
  { id: 124, c: "reglas", t: "Dentro de un set el orden de saque no se cambia, pero al empezar uno nuevo pueden elegir quién saca primero. Si alguien saca fuera de turno, se corrige en cuanto se note.", f: "g3", p: 9 },
  { id: 125, c: "saque-resto", t: "Con un saque al vidrio lateral, si la bola toca pared el resto se complica; si el rival pega muy atrasado, suele devolver en paralelo y se vuelve predecible.", f: "g3", p: 21 },
  { id: 126, c: "tecnica", t: "En los rebotes de pared, dejá la pelota delante tuyo: la secuencia ideal es pared, vos y pelota. Si la dejás pasar a tu espalda, llegás apurado y sin fuerza.", f: "libro", p: 76 },
  { id: 127, c: "mental", t: "El pádel es más que técnica: también cuentan la táctica, el físico y la cabeza, y se influyen entre sí. Entrená los cuatro aspectos y no te quedes solo con los golpes.", f: "g1", p: 10 },
  { id: 128, c: "remate", t: "Buscá la pelota en el punto más alto, con el brazo bien extendido. Golpeando desde arriba le das un ángulo descendente a la bola.", f: "g4", p: 7 },
  { id: 129, c: "posicion", t: "Después de pegar, frená rápido y volvé hacia el centro de tu zona, tratando de llegar antes de que el rival golpee. Volvé al punto medio entre las salidas posibles de la pelota.", f: "libro", p: 69 },
  { id: 130, c: "tecnica", t: "Frená y ajustá con pasitos cortos antes de pegar. Mucha gente se concentra solo en el brazo y se olvida de que los pies arman el golpe.", f: "g3", p: 5 },
  { id: 131, c: "posicion", t: "Si ves que una pelota puede morir en el pico de la pared y quedar a media cancha, avisale a tu compañero con un grito para que cubra el centro y la recupere.", f: "g1", p: 16 },
  { id: 132, c: "reglas", t: "Si al saque la pelota te toca a vos o a tu compañero antes de picar, el punto es para el sacador. Y el resto no se puede volear, aunque estés fuera del cuadro.", f: "g3", p: 11 },
  { id: 133, c: "posicion", t: "Pegarte demasiado a la red te deja sin tiempo para volear y es una invitación al globo profundo. Elegí una distancia desde la que llegues cómodo a la volea y al remate.", f: "g1", p: 16 },
  { id: 134, c: "mental", t: "Antes de un partido, imaginate los golpes que querés hacer. Visualizar la jugada ayuda a activar el cuerpo y a ganar confianza.", f: "libro", p: 114 },
  { id: 135, c: "saque-resto", t: "En el resto, armado corto y terminación larga. La pelota ya viene con velocidad, así que muchas veces alcanza con acompañarla hacia el campo rival.", f: "g3", p: 24 },
  { id: 136, c: "mental", t: "Concentrate al máximo en los dos primeros puntos cuando estás al resto. Empezar el game arriba mete presión al sacador y a veces lo hace dudar de su juego.", f: "g3", p: 27 },
  { id: 137, c: "reglas", t: "Con una pelota rota o algo ajeno que entra a la cancha, avisá enseguida para repetir el punto. Si dejás seguir el juego, perdés el derecho a reclamarlo.", f: "g3", p: 12 },
  { id: 138, c: "tactica", t: "Si le pegás fuerte desde el fondo, no subas pegado a tu bola: hacé una pausa y mirá la respuesta. Si te vuelven una buena volea, seguís con el punto bien parado atrás.", f: "g2", p: 42 },
  { id: 139, c: "tecnica", t: "Una forma de trabajar el golpe: gravate con el celular y mirá si levantás el codo, no flexionás las piernas o pegás muy adelante o atrás. Después corregilo en cancha.", f: "g3", p: 40 },
  { id: 140, c: "posicion", t: "Tip para medir tu distancia al fondo: con la pala estirada hacia atrás no deberías tocar el vidrio. Ni pegado a la pared, ni demasiado lejos.", f: "g2", p: 27 },
  { id: 141, c: "saque-resto", t: "Probá sacar al cuerpo del rival: muchas veces no tiene ángulo para pegarle y se encuentra apurado, sobre todo si le dejás poco espacio.", f: "g3", p: 17 },
  { id: 142, c: "tecnica", t: "En la pared lateral, el golpe se arma corto: usá el impulso que ya trae la bola, sin preparar un swing largo. Mirá bien la trayectoria, la velocidad y el efecto con que llega.", f: "libro", p: 149 },
  { id: 143, c: "tactica", t: "Elegí el golpe según cómo te llegó la bola. Si te sacaron de posición, tirá un globo para recuperar tu lugar; una pelota rápida y rasa no te da tiempo de volver.", f: "g1", p: 3 },
  { id: 144, c: "remate", t: "Mientras te perfilás para el remate, estirá el brazo que no usa la pala hacia arriba. Te da equilibrio y te marca a qué distancia está la pelota.", f: "g4", p: 7 },
  { id: 145, c: "posicion", t: "Para la pelota del medio no hay dueño fijo: va quien esté más atento, y si viene en ángulo, el que está cruzado. Gritá un claro \"mía\" o \"vas vos\" para no dudar.", f: "g1", p: 16 },
  { id: 146, c: "tecnica", t: "Detrás en el fondo flexioná más las piernas y llevá la pala más baja; en la red tenela más alta. Así te adaptás a la bola que viene.", f: "g3", p: 3 },
  { id: 147, c: "tactica", t: "En cancha descubierta, fijate hacia dónde va el viento y de qué lado te da el sol. Con viento en contra jugá más fuerte, a favor más suave; si el sol les da de frente a ellos, tirá globos.", f: "g1", p: 22 },
  { id: 148, c: "tecnica", t: "Pegale a la bola cuando va subiendo, no en el punto más alto. Si esperás a que baje, llega sin fuerza y le das más tiempo al rival para acomodarse.", f: "g1", p: 16 },
  { id: 149, c: "etiqueta", t: "Tratá a tu compañero como te gustaría que te traten. Evitá las caras de fastidio y los comentarios por lo bajo cuando falla: eso solo suma errores para los dos.", f: "g1", p: 3 },
  { id: 150, c: "tactica", t: "Subir a la red no es sinónimo de atacar. Ahí tu laburo principal es cubrir espacios y bloquear los golpes rápidos; defini solo cuando el rival te deje una bola lenta.", f: "g2", p: 39 },
  { id: 151, c: "tecnica", t: "Cuando defendés contra el vidrio, armá corto y ajustá la altura del armado a cómo rebota la pelota. Si viene baja, la pala tiene que ir baja.", f: "g3", p: 69 },
  { id: 152, c: "tactica", t: "Con pelotas muy usadas o mojadas no intentes traerte el remate a tu campo. Pican poco y lo más probable es que te pierdas la red.", f: "g4", p: 11 },
  { id: 153, c: "tecnica", t: "Cuidado con las malas costumbres de agarre: corregir una empuñadura es de lo más difícil. Conviene aprenderla bien desde el principio antes que desaprenderla después.", f: "libro", p: 55 },
  { id: 154, c: "tactica", t: "La cruzada es tu dirección base: tenés más cancha, más tiempo y el rival más lejano. Usá la paralela para cambiar el juego, por ejemplo cuando a tu compañero lo están martillando.", f: "libro", p: 84 },
  { id: 155, c: "tecnica", t: "Evitá golpear con el cuerpo de frente o cerrado: el peso no pasa hacia adelante. Ponete de costado a la pelota para transferir la fuerza y mantener el equilibrio.", f: "libro", p: 68 },
  { id: 156, c: "tactica", t: "Antes de empezar mirá a los rivales en la entrada en calor: si son zurdos, qué golpes usan, cuál es su punto flojo (casi siempre el revés) y si se sienten mejor defendiendo o atacando.", f: "g3", p: 64 },
  { id: 157, c: "tecnica", t: "En los golpes de fondo, repetí por dentro el ritmo bota, paro, pego: dejá picar, frená de lado y recién ahí golpeá, cargando el peso hacia adelante.", f: "libro", p: 61 },
  { id: 158, c: "tactica", t: "Si quedaron los dos juntos en el medio o fuera de lugar, tiren un globo. Les da tiempo para volver a sus posiciones antes de que el rival aproveche los huecos.", f: "g2", p: 32 },
  { id: 159, c: "tecnica", t: "En el globo, empujá la pelota en vez de pegarle, con la pala abierta y acompañando con la extensión de piernas. Buscá que salga alta, profunda y que casi no rebote.", f: "libro", p: 187 },
  { id: 160, c: "tactica", t: "Conocete antes de salir a jugar: cuáles son tus mejores y peores golpes, si te sentís más cómodo defendiendo o atacando, y cuánta fuerza podés usar sin perder control.", f: "g1", p: 20 },
  { id: 161, c: "posicion", t: "Practicá con tu compañero cómo moverse cuando el rival va a rematar: lo que hacés vos depende de lo que haga él. Esa coordinación se entrena.", f: "g4", p: 17 },
  { id: 162, c: "saque-resto", t: "Sacá a la T para llevar al rival al centro y dejar el rincón libre. Sacá a los pies para generar dudas entre derecha y revés, pero usalo de a ratos.", f: "g3", p: 21 },
  { id: 163, c: "posicion", t: "Después de un remate forzado, lo peor es quedarte a media cancha. Subí enseguida a la red o retrocedé a defender con calma.", f: "g4", p: 12 },
  { id: 164, c: "lesiones", t: "Calentá entre 10 y 15 minutos antes de jugar: trote suave, movilidad de articulaciones y recién ahí un peloteo con todos los golpes. No te saltees este paso.", f: "g1", p: 34 }
];

// Consejo del día: uno por día (hora de Argentina), siempre el mismo para todos.
export function consejoDelDia(ahora = Date.now()) {
  const dia = Math.floor((ahora - 3 * 3600 * 1000) / 86400000);
  return CONSEJOS[dia % CONSEJOS.length];
}

// "Basado en PadelStar · Guía 4: El remate de pádel (p. 7)"
export function fuenteDe(c) {
  return FUENTES[c.f];
}
